### ISSUE TITLE
installation in subfolder, relative paths

### ISSUE THREAD

**Issue by nbbn** [twostairs/paperwork#256]
Hello,
please treat it as a question or enhancement request.
I tried installation of paperwork in subdirectory, e.g. example.com/hidden/paperwork/.

It's not a problem to cut off frontend/public by webserver's config (what will be explained later).
There is line in paperwork/frontend/app/config/app.php, that allows to modify path:
```
url' => 'https://example.com/hidden/paperwork/frontend/public',
```
it allows to correctly point css/js files.

Things that still need to be fixed: 
  - API requests
  - urls to woff files in css
  - images' urls, for example:
```
in app/views/layouts/user-layout.blade.php:
<img src="/images/navbar-logo.png">
I don't know Laravel, but quick, ugly fix works:
<img src="<?php echo(asset('images/navbar-logo.png'));?>">
```

API and images are fixed in [Whisprin/paperwork](https://github.com/Whisprin/paperwork/commit/8445d3197e3aaca66dca7a6ce5b0a50ff337b8c2) by just using relative paths, what could be problem with mod_rewrite beutiful urls, not here. Relative paths to fonts could be fixed in the same way.

I've noticed that question from A&Q:
Can I run Paperwork on a shared host environment, where I'm not able to set frontend/public as document root?

In some way touches this matter. I think [it could be possible to use .htaccess to solve this problem](http://stackoverflow.com/questions/7710411/how-to-remove-part-of-url-with-htaccess), what is often allowed in shared hosting.

Maybe it's a good idea to officially suppport installation in subdirectory, or maybe I'm missing something out?

**Comment by konfiot** [comment]
I support the Idea, It would be great as it would allow to use paperwork alongside with other self-hosted applications

**Comment by Baldrs** [comment]
Fixed in #360

**Comment by Liongold** [comment]
It's better if the issue is closed when the pull request is merged.

**Comment by Baldrs** [comment]
Merged

**Comment by stephane-martin** [comment]
hi,
i still don't get correct URL for API calls. For example, the URLs to download attachments don't have the instance prefix.
