### ISSUE TITLE
Various errors causing a WSOD

### ISSUE THREAD

**Issue by whodafly** [twostairs/paperwork#659]
_Using PHP 7.0_

I am getting a WSOD, so I ran a syntax check of all files (as suggested by a comment on Stackoverflow), and I found the following errors:

There's a syntax error on line 11 in app/lang/nl/validation.php:

``` php
$name_error_message.: "bevatten";
                    ^
```

Should be (I think, I'm not a PHP developer):

``` php
$name_error_message.= "bevatten";
                    ^
```

Then there are a couple of errors I don't know how to fix:

```
PHP Fatal error: Constructor Input::input() cannot be static in _ide_helper.php on line 6091
PHP Fatal error: Cannot use 'String' as class name as it is reserved in vendor/symfony/translation/Symfony/Component/Translation/Tests/TranslatorTest.php on line 466
PHP Fatal error: Cannot redeclare iconv() in vendor/patchwork/utf8/src/Patchwork/Utf8/Bootup/iconv.php on line 21
PHP Fatal error: Cannot redeclare utf8_encode() in vendor/patchwork/utf8/src/Patchwork/Utf8/Bootup/utf8_encode.php on line 16
```

Based on the date of the last commit I see in the repo, I'm guessing you guys haven't checked this with PHP 7?

**Comment by Liongold** [comment]
Unfortunately, I don't think any tests with PHP7 have been done. About the first error, can you change the file on your install and test it. It could be the solution (and leave a space between the variable name and the `.`). 

@mrusme Can this be fixed in the repo or should it be handled by the translation service?

About the other errors, they haven't been reported yet. Can you try running Paperwork by only making the change described above (and thus ignoring the last errors), please?

**Comment by whodafly** [comment]
@Liongold I had already fixed the first problem before I logged the issue. It didn't help, I still get a WSOD.

**Comment by Liongold** [comment]
The other problems are actually not caused by Paperwork but its dependencies. They are only PHP7 issues, it seems. Can you use another version of PHP (5.6 should work)?

**Comment by whodafly** [comment]
No, I can't.

**Comment by Liongold** [comment]
Laravel still needs to be upgraded to a version supporting PHP7. This is handled in #54. The first error could be avoided by removing the _ide_helper.php file, probably. In theory, Laravel could be changed to avoid using 'String', but it might require a number of changes. Would you be interested to do these on your side (with guidance) and test them?

**Comment by Liongold** [comment]
Just for you (or anyone else who wants to test it), that error should be avoided by opening the file mentioned in the error, `vendor/symfony/translation/Symfony/Component/Translation/Tests/TranslatorTest.php`, and on line 466, replace `class String` with `class StringClass`. Anyone who tests it, please reply with the results.

**Comment by whodafly** [comment]
Renamed the String to StringClass and removed the _ide_helper.php file, but I'm still getting a WSOD (and I can't figure out how to make it actually log to the log file -- everything I've tried hasn't worked).

**Comment by Liongold** [comment]
Can you recompile PHP without iconv?

**Comment by Liongold** [comment]
@whodafly The Laravel developers have updated Laravel 4.2 to be compatible with PHP 7. Thus, there should not be any issues anymore. If you test it again and find any issues, please open a new issue. This report will be closed. Thanks for your feedback.
